In [143]:
import numpy as np

In [ ]:
x = np.array=([5, 4, -7, 11])
print(x)


In [ ]:
x2 = np.array=([2, 2, 3, -5, 6, 8])
print(x2)

In [ ]:
y = np.array=([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

In [ ]:
y2 = np.array=([[2,3,4], [84, -5, 6], [8-5, -8, 9]])
print(y2)

In [ ]:
z = np.array=([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

In [ ]:
z2 = np.array=([[[2, 4, 5], [8, 9, 10], [2, 4, 6]], [[11, 13, 16], [80, 87, 98], [12, 13, 45]]])
print(z2)

In [ ]:
b = np.arange(10).reshape(2, 5) 
print(b)

In [ ]:
p = np.arange(30).reshape(3,10)
print(p)

In [ ]:
type(b)

In [ ]:
b.shape

In [ ]:
b.size

In [ ]:
b.ndim

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [ ]:
p = np.arange(1, 19).reshape((3, 3, 2))
print(p)

In [ ]:
p.shape

In [ ]:
p.size

In [ ]:
p.ndim

In [ ]:
z = np.array=([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

Exercise2:Extract the value 15 from the z array above by indexing

In [ ]:
z[1,1,2]

In [ ]:
##array slice

In [ ]:
z[1, 2, :]

In [ ]:
y[:2, :]

In [ ]:
y[1:, :]

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [ ]:
##vectorizing and summarizing

In [ ]:
x+2

In [ ]:
x-1

In [ ]:
x**2

In [ ]:
np.abs(x)

In [ ]:
np.max(x)

In [ ]:
np.median(x)

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

In [ ]:
b = np.array=[2, 4, 5, 6, 8, 9]
array_len = len(b)

if array_len == 0:
    median = (b[int(array_len/2)] + b[int(array_len/2-1)]/2)
else: 
    median = b[int(array_len/2)]
print(median)

    

Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [144]:
x = np.array=[2, 3, 4, 5, 6, 7, 8, 9]
np.median(x)

5.5

In [ ]:
~ bedeutet "nicht",  | bedeutet ist "oder", & bedeutet und (conditional statements python nochmal nachschauen)

In [145]:
x<5 

TypeError: '<' not supported between instances of 'list' and 'int'

In [146]:
x==11

False

In [ ]:
~(x > 1)

In [ ]:
##masks for subsetting

In [ ]:
x[x < 5]

In [ ]:
x[x < 5]=40
x


Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [ ]:
new = x [~(x>20) | (x==20)]=30

In [148]:
np.sum(x)

44

In [149]:
np.sum(x<35) #alle Elemente die kleiner sind als 35 sollen zusammengezählt werden

TypeError: '<' not supported between instances of 'list' and 'int'

In [155]:
y = np.array=([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)



[[4, 5, 0], [3, 7, 9], [2, 1, 2]]


In [156]:
z = np.array=([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]


In [150]:
np.sum(y, axis=0)

array([ 9, 13, 11])

In [151]:
np.sum(y, axis=1)

array([ 9, 19,  5])

In [152]:
##row-column
np.sum(z, axis=0)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [153]:
##column-layer
np.sum(z, axis=1)

array([[12, 15, 18],
       [39, 42, 45]])

In [154]:
##row-layer
np.sum(z, axis=2)

array([[ 6, 15, 24],
       [33, 42, 51]])

Exercise7: Calculate the mean of all column in each layer from array z.

In [ ]:
## ploting an array

In [157]:
import matplotlib.pyplot as plt

TypeError: 'list' object is not callable

In [ ]:
h = y.flatten()
h

In [ ]:
plt.hist(h);

In [158]:
plt.plot(y[1, :]);

NameError: name 'plt' is not defined

In [159]:
plt.plot(y[:, 1]);

NameError: name 'plt' is not defined

In [160]:
plt.plot(y);

NameError: name 'plt' is not defined

In [161]:
plt.imshow(y);

NameError: name 'plt' is not defined

In [162]:
##practice with plotting on different arrays

In [163]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

plt.hist(data, bins=[0,2,4,6,8,10])
plt.title('My Histogram')
plt.xlabel('Interval')
plt.ylabel('Frequency')
plt.show()


TypeError: 'list' object is not callable

Exercise8: Given an 2D array of numbers, plot a graph that displays the sum of each element in the column.


Reference: https://docs.python.org
https://geobgu.xyz/py/numpy.html 