In [1]:
## Numeric int, float

In [17]:
a=1
type(a)


int

In [20]:
n = 5
type(n) #or type(5)

int

In [3]:
b= 2.8
type(2.8)

float

In [21]:
c = 56.8
type(c)

float

In [4]:
## Sequence list, tuple

In [5]:
type([4, 6, 7])

list

In [22]:
type([3, 2.7, 4, 28, 29])

list

In [23]:
type((1, 5))

tuple

In [24]:
t = ((2, 5, 6, 8, 9, 10, 2.8))
type(t)

tuple

In [7]:
## String str

In [8]:
type("I like Math!")


str

In [25]:
string = ("i like geography")
type(string)

str

In [9]:
## Mapping dict

In [10]:
type({"number of student": 8, "p": 5})

dict

In [26]:
dict=({"gas": 1, "math": 9})
type(dict)

dict

In [11]:
##set

In [12]:
type({"number of student", "p"})

set

In [27]:
set=({"arania", "2", "nothing"})
type(set)

set

In [13]:
##Boolean 

In [14]:
1 == 2

False

In [28]:
200 == 200

True

In [15]:
c=("I like Math!")

In [16]:
print(c[2])

l


In [32]:
b = ("i like geography")
print(b[5])

e


Excercise1: Assign a list to a variable and check the type and print an element using index!

In [34]:
c = [2, 5, 7, 8, 9]
print(type(c))
print(c[3])

<class 'list'>
8


Excercise2: Assign a flot to a variable and use the print() function to print out the following sentence "the type of 2.8 is <class 'float'>"

In [40]:
g = ([2.8, 2.9, 2.7, 2.6])
print("the type of", g[2], "is", type(c[2]))

the type of 2.7 is <class 'int'>


In [ ]:
##Arithmetic operators

In [45]:
1+5*4

21

In [46]:
2+2+2+2+2+2*600

1210

In [47]:
(1+5)*4

24

In [48]:
30%10

0

In [49]:
10%30

10

In [53]:
16.4//2

8.0

In [54]:
4**3

64

In [ ]:
##Conditional Statements 

In [41]:
grade=60

if grade>50:
    print("you pass the test")

you pass the test


In [42]:
a=34
if a<20:
    print("you are a winner")
else:
    print("you are a loser")
    

you are a loser


In [56]:
grade=60

if grade>50:
    print("you pass the test")

you pass the test


Excercise3: Given two numbers a and b, write a Python code to check if a is divisible by b

In [61]:
a = 3
b = 4
if (a % b == 0):
    print("divisible")
else:
    print("not divisible")

not divisible


In [ ]:
## for and while loop

In [62]:
animals = ["dog", "cat", "bird"]
for x in animals:
    print(x)

dog
cat
bird


In [63]:
animals = ["dog", "cat", "bird"]
for x in animals:
    print(x)
    if x == "cat":
        break

dog
cat


In [66]:
x = range(10, 21)
for n in x:
    print(n)

10
11
12
13
14
15
16
17
18
19
20


In [71]:
y = range(200, 211)
for p in y:
    print(p)
    if p == 203:
        break

200
201
202
203


In [75]:
x = range(10, 20,5)
for n in x:
    print(n)

10
15


Exercise4: What numbers between 2 and 30 are even and odd?

In [85]:
t = range(2,31)
for p in t:
    if p % 2 == 0:
        print(p, "is even")
    else:
        print(p, "is odd")

2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even
11 is odd
12 is even
13 is odd
14 is even
15 is odd
16 is even
17 is odd
18 is even
19 is odd
20 is even
21 is odd
22 is even
23 is odd
24 is even
25 is odd
26 is even
27 is odd
28 is even
29 is odd
30 is even


In [81]:
i = 1
while i < 11:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


Exercise5:print out the numbers from 100 to 0 in steps of 10, using while loop



In [90]:
i = 100
while i >= 0:
    print(i)
    i -= 10

100
90
80
70
60
50
40
30
20
10
0


In [ ]:
## Def function

In [87]:
def add_numbers(num1, num2):
    sum = num1 + num2
    return sum
print(add_numbers(3, 5))

8


Exercise6:What is the area of a rectangle with a length of 2 and a width of 4? (use def function)

In [91]:
def area_rect(num1, num2):
    mul = num1 * num2
    return mul
print(area_rect(2, 4))

8


In [ ]:
## Python Arrays

In [92]:
array_ex = [1, 2, 3, 4, 5]
print(array_ex)

[1, 2, 3, 4, 5]


In [93]:
x = array_ex[0]
print(x)

1


In [94]:
x = len(array_ex)
print(x)

5


In [95]:
array_ex.append(5)
print(array_ex)

[1, 2, 3, 4, 5, 5]


In [1]:
new = [4, 5, 6, 7, 8, 9]
new.append(99)
print(new)

[4, 5, 6, 7, 8, 9, 99]


In [96]:
array_ex.pop(1)
print(array_ex)

[1, 3, 4, 5, 5]


In [2]:
new_2 = [1, 2, 3, 4, 5, 6, 7]
new_2.pop(2)
print(new_2)

[1, 2, 4, 5, 6, 7]


Exercise7:Write a Python program to find the largest number in a given array of numbers

In [18]:
test = [1, 2, 3, 4, 5, 6, 7, 8]
for t in test:
    if t > max-1:
        print(t)

8


andere Lösung

In [20]:
arr = [2, 4, 6, 8]
max_num = arr[0]

for num in arr:
    if num > max_num:
        max_num = num
print(max_num)
    

8


In [1]:
import numpy as np

In [2]:
x = np.array([5, 4, -7, 11])
print(x)

[ 5  4 -7 11]


In [3]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [4]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
g = np.arange(20) #array mit 20 Werten
print(g)
f = np.arange(2, 10, 2) #Array mit Werten zwischen 2 und 10 in 2er Schritten
print(f)
h = np.linspace(0,20,5) #5 Werte in einem Array von 0 bis 20
print(h)
z= np.zeros(3) #array mit 3 Nullen
print(z)
o= np.ones(7) #array mit 7 einsen
print(o)
l= np.empty(8) #mit 8 zufälligen Werten
print(l)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 4 6 8]
[ 0.  5. 10. 15. 20.]
[0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[4.66662101e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]


In [7]:
type(b)

numpy.ndarray

In [8]:
b.ndim

2

In [9]:
b.size

10

In [10]:
b.dtype

dtype('int64')

In [11]:
b = b.astype(np.float64)
print(b)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


Exercise8:Create a 3-dimensional array using np.arange() and reshape

In [12]:
exc = np.arange(36).reshape(3,12)
print(exc)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]


Exercise9:Create an array of dictionaries and print it

In [13]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise10:Extract the value 15 from the z array above by indexing

In [49]:
#nummer 15
z[1,1,2]
#nummer 9
z[0,2,2]
#nummer 17
z[1,2,1]

17

In [5]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
##array slice

In [6]:
z[1, 2, :]

array([16, 17, 18])

In [9]:
z[:2, :]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
z[1:, :]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Exercise11:Extract the first and 2rd rows and all columns from the z array above by indexing

In [2]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [7]:
print(z[0:2,:2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


In [41]:
z[1,1,2]

15

Übung Indexing

In [25]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
x[2]

2

In [27]:
x[-2]

8

In [28]:
x.shape = (2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
x[0,4]

4

In [50]:
x[1, -2]

8

Wenn man ein mehrdimensionales Array mit weniger Indizes als Dimensionen indiziert, 
erhält man ein unterdimensionales Array. Zum Beispiel:

In [51]:
x[0]

array([0, 1, 2, 3, 4])

In [54]:
t = np.arange(21)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [59]:
i = 50
while i >= 0:
    print(i)
    i-=5

50
45
40
35
30
25
20
15
10
5
0


In [76]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
def neu(x, y):
    calc = x/y
    return calc
print(neu(2,3))

0.6666666666666666


Übung Slice

Aus einer Liste einen Teil extrahieren

Übung Indexing 

In [5]:
import numpy as np
# boolean 
x = np.arange(25)
greater_than_five = x > 5
print(greater_than_five)

#where
drop_under_5_array = np.where(x > 5, x, 0) #aus unseren Daten x alle die unter 5 sind zu 0
print(drop_under_5_array)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]
[ 0  0  0  0  0  0  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
